package com.github.webicitybrowser.spec.html.parse;

public enum ParseError {
	
	UNEXPECTED_NULL_CHARACTER,
	EOF_IN_TAG,
	NON_VOID_HTML_ELEMENT_START_TAG_WITH_TRAILING_SOLIDUS,
	UNEXPECTED_SOLIDUS_IN_TAG,
	MISSING_WHITESPACE_BETWEEN_ATTRIBUTES,
	ABRUPT_CLOSING_OF_EMPTY_COMMENT,
	EOF_IN_COMMENT,
	NESTED_COMMENT,
	INCORRECTLY_CLOSED_COMMENT,
	MISSING_ATTRIBUTE_VALUE,
	UNEXPECTED_CHARACTER_IN_UNQUOTED_ATTRIBUTE,
	MISSING_SEMICOLON_AFTER_CHARACTER_REFERENCE,
	ABSENCE_OF_DIGITS_IN_NUMERIC_CHARACTER_REFERENCE,
	UNKNOWN_NAMED_CHARACTER_REFERENCE,
	EOF_IN_SCRIPT_HTML_COMMENT_LIKE_TEXT

}
