package com.github.webicitybrowser.spec.html.parse;

public enum ParseError {
	
	UNEXPECTED_NULL_CHARACTER,
	EOF_IN_TAG,
	NON_VOID_HTML_ELEMENT_START_TAG_WITH_TRAILING_SOLIDUS,
	UNEXPECTED_SOLIDUS_IN_TAG,
	MISSING_WHITESPACE_BETWEEN_ATTRIBUTES,
	ABRUPT_CLOSING_OF_EMPTY_COMMENT,
	EOF_IN_COMMENT,
	NESTED_COMMENT,
	INCORRECTLY_CLOSED_COMMENT

}
